import os
"""DSV4 oracle model: official model.py + loop-TP8 lazy-bound parallel layers.
Generated by make_arch.py from official_model.py; forward semantics unchanged.
"""
import math
from dataclasses import dataclass
from typing import Tuple, Optional, Literal
from functools import lru_cache
from contextlib import contextmanager

import torch
from torch import nn
import torch.nn.functional as F
import torch.distributed as dist

from .kernels_torch import act_quant, fp4_act_quant, fp8_gemm, fp4_gemm, sparse_attn
from .kernels_torch import rotate_activation
from .qmath import dequant_fp8
from .past import SlotPool


world_size = 1
rank = 0


def init_distributed():
    """Call after dist.init_process_group; switches parallel layers to NCCL mode."""
    global world_size, rank
    world_size = dist.get_world_size()
    rank = dist.get_rank()


block_size = 128
fp4_block_size = 32
default_dtype = torch.bfloat16
scale_fmt = None
scale_dtype = torch.float32


@contextmanager
def set_dtype(dtype):
    """Temporarily override torch default dtype, restoring it on exit (even if an exception occurs)."""
    prev = torch.get_default_dtype()
    torch.set_default_dtype(dtype)
    try:
        yield
    finally:
        torch.set_default_dtype(prev)

@dataclass
class ModelArgs:
    """Model hyperparameters. Field names match the config JSON keys."""
    max_batch_size: int = 4
    max_seq_len: int = 4096
    # Paged-KV pool budget in tokens, shared by ALL slots (slots may be of very
    # different lengths). Decoupled from max_batch_size on purpose: the pool is a
    # memory budget, max_seq_len is only the per-sequence cap. 0 = legacy
    # n_slots * max_seq_len (page table can never be exhausted, but wastes VRAM).
    pool_tokens: int = 0
    temperature: float = 1
    dtype: Literal["bf16", "fp8"] = "fp8"
    scale_fmt: Literal[None, "ue8m0"] = "ue8m0"
    expert_dtype: Literal[None, "fp4"] = None
    scale_dtype: Literal["fp32", "fp8"] = "fp8"
    vocab_size: int = 129280
    dim: int = 4096
    moe_inter_dim: int = 4096
    n_layers: int = 7
    n_hash_layers: int = 0
    n_mtp_layers: int = 1
    n_heads: int = 64
    # moe
    n_routed_experts: int = 8
    n_shared_experts: int = 1
    n_activated_experts: int = 2
    score_func: Literal["softmax", "sigmoid", "sqrtsoftplus"] = "sqrtsoftplus"
    route_scale: float = 1.
    swiglu_limit: float = 0.
    # mqa
    q_lora_rank: int = 1024
    head_dim: int = 512
    rope_head_dim: int = 64
    norm_eps: float = 1e-6
    o_groups: int = 8
    o_lora_rank: int = 1024
    window_size: int = 128
    compress_ratios: Tuple[int] = (0, 0, 4, 128, 4, 128, 4, 0)
    # yarn
    compress_rope_theta: float = 40000.0
    original_seq_len: int = 0
    rope_theta: float = 10000.0
    rope_factor: float = 40
    beta_fast: int = 32
    beta_slow: int = 1
    # index
    index_n_heads: int = 64
    index_head_dim: int = 128
    index_topk: int = 512
    # hc
    hc_mult: int = 4
    hc_sinkhorn_iters: int = 20
    hc_eps: float = 1e-6
    # dspark
    dspark_block_size: int = 0
    dspark_noise_token_id: int = 0
    dspark_target_layer_ids: Tuple[int] = tuple()
    dspark_markov_rank: int = 256


class ParallelEmbedding(nn.Module):
    """Loop-TP8: weight is a list of per-GPU shards [vocab/8, dim]; partial embed + sum."""
    def __init__(self, vocab_size: int, dim: int):
        super().__init__()
        self.vocab_size = vocab_size
        self.dim = dim
        self.weight = None  # bound by loader: list[Tensor]

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if not isinstance(self.weight, list):  # NCCL: weight is this rank's shard
            if self.weight.size(0) == self.vocab_size:  # full table replicated (bind gathers it): no mask / all_reduce
                return F.embedding(x, self.weight)
            part = self.vocab_size // world_size
            xi = x - rank * part
            mask = (xi < 0) | (xi >= part)
            y = F.embedding(xi.clamp(0, part - 1), self.weight)
            y[mask] = 0
            dist.all_reduce(y)
            return y
        n = len(self.weight)
        part = self.vocab_size // n
        y = None
        for i, w in enumerate(self.weight):
            xi = x.to(w.device) - i * part
            mask = (xi < 0) | (xi >= part)
            yi = F.embedding(xi.clamp(0, part - 1), w)
            yi[mask] = 0
            y = yi.to(x.device) if y is None else y + yi.to(x.device)
        return y


def linear(x: torch.Tensor, weight: torch.Tensor, bias: Optional[torch.Tensor] = None) -> torch.Tensor:
    """Dispatches to fp4_gemm / fp8_gemm / F.linear based on weight dtype.
    For quantized weights, x is first quantized to FP8 via act_quant."""
    assert bias is None

    if weight.dtype == torch.int8 or weight.dtype == torch.float4_e2m1fn_x2:
        x, s = act_quant(x, block_size, scale_fmt, scale_dtype)
        return fp4_gemm(x, s, weight, weight.scale, scale_dtype)
    elif weight.dtype == torch.float8_e4m3fn:
        x, s = act_quant(x, block_size, scale_fmt, scale_dtype)
        return fp8_gemm(x, s, weight, weight.scale, scale_dtype)
    elif getattr(weight, "qdq_block", None) is not None:
        # fp8 Linear pre-dequantized to bf16 at load (bind._fp8lin); act qdq + gemm in one leaf.
        assert weight.qdq_block == block_size and weight.dtype == torch.bfloat16, (weight.qdq_block, weight.dtype)
        import ops
        return ops.fp8_linear(x, weight)
    else:
        return F.linear(x, weight)


class Linear(nn.Module):
    """Lazy linear: weight bound by loader. fp8/fp4 weight tensors carry a .scale attribute."""

    def __init__(self, in_features: int, out_features: int, bias: bool = False, dtype = None):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.dtype = dtype or default_dtype
        self.weight = None
        self.bias = None

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return linear(x, self.weight, self.bias)


class ColumnParallelLinear(Linear):
    """Loop-TP8: weight is list of shards [out/8, in]; concat outputs on last dim."""
    def __init__(self, in_features: int, out_features: int, bias: bool = False, dtype = None):
        assert out_features % world_size == 0, f"Output features must be divisible by world size (world_size={world_size})"
        self.part_out_features = out_features // world_size
        super().__init__(in_features, self.part_out_features, bias, dtype)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if not isinstance(self.weight, list):  # NCCL: local shard, output stays local
            return linear(x, self.weight)
        ys = [linear(x.to(w.device), w).to(x.device) for w in self.weight]
        return torch.cat(ys, dim=-1)


class RowParallelLinear(Linear):
    """Loop-TP8: weight is list of shards [out, in/8]; sum partial results in fp32 (matches TP8 all_reduce)."""
    def __init__(self, in_features: int, out_features: int, bias: bool = False, dtype = None, reduce: bool = True):
        assert in_features % world_size == 0, f"Input features must be divisible by world size (world_size={world_size})"
        self.part_in_features = in_features // world_size
        super().__init__(self.part_in_features, out_features, bias, dtype)
        self.reduce = reduce

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if not isinstance(self.weight, list):  # NCCL: x is already this rank's slice
            y = linear(x, self.weight).float()
            if not self.reduce:
                # partial sum in fp32; caller (MoE) merges via its final all_reduce
                if self.bias is not None:
                    y += self.bias
                return y
            T = y.numel() // y.shape[-1]
            if (self.bias is None and x.dtype == torch.bfloat16 and not torch.cuda.is_current_stream_capturing()
                    and T % world_size == 0 and T >= 8 * world_size):
                # prefill (large T, not graph-captured): fp32 reduce_scatter over rows -> local bf16
                # round -> bf16 all_gather. Same fp32-sum-then-bf16-round as all_reduce + type_as,
                # gather phase moves half the bytes. Reduction order may differ from AR (1-ulp).
                y2 = y.view(T, -1)
                part = torch.empty(T // world_size, y2.shape[1], dtype=torch.float32, device=y.device)
                dist.reduce_scatter_tensor(part, y2)
                out = torch.empty(T, y2.shape[1], dtype=torch.bfloat16, device=y.device)
                dist.all_gather_into_tensor(out, part.to(torch.bfloat16))
                return out.view(y.shape)
            dist.all_reduce(y)
            if self.bias is not None:
                y += self.bias
            return y.type_as(x)
        xs = x.chunk(len(self.weight), dim=-1)
        y = None
        for xc, w in zip(xs, self.weight):
            p = linear(xc.to(w.device), w).float().to(x.device)
            y = p if y is None else y + p
        if self.bias is not None:
            y += self.bias
        return y.type_as(x)


class RMSNorm(nn.Module):
    def __init__(self, dim: int, eps: float = 1e-6):
        super().__init__()
        self.dim = dim
        self.eps = eps
        # rmsnorm in the checkpoint is stored in bf16, while the parameter here is stored in fp32 for convenient.
        self.weight = nn.Parameter(torch.ones(dim, dtype=torch.float32))

    def forward(self, x: torch.Tensor):
        import ops
        return ops.rms_norm(x.contiguous(), self.weight, self.eps)


@lru_cache(2)
def precompute_freqs_cis(dim, seqlen, original_seq_len, base, factor, beta_fast, beta_slow) -> torch.Tensor:
    """Precomputes complex exponentials for rotary embeddings with YaRN scaling.
    When original_seq_len > 0, applies frequency interpolation with a smooth
    linear ramp between beta_fast and beta_slow correction ranges."""

    def find_correction_dim(num_rotations, dim, base, max_seq_len):
        return dim * math.log(max_seq_len / (num_rotations * 2 * math.pi)) / (2 * math.log(base))

    def find_correction_range(low_rot, high_rot, dim, base, max_seq_len):
        low = math.floor(find_correction_dim(low_rot, dim, base, max_seq_len))
        high = math.ceil(find_correction_dim(high_rot, dim, base, max_seq_len))
        return max(low, 0), min(high, dim-1)

    def linear_ramp_factor(min, max, dim):
        if min == max:
            max += 0.001
        linear_func = (torch.arange(dim, dtype=torch.float32) - min) / (max - min)
        ramp_func = torch.clamp(linear_func, 0, 1)
        return ramp_func

    freqs = 1.0 / (base ** (torch.arange(0, dim, 2, dtype=torch.float32) / dim))
    if original_seq_len > 0:
        low, high = find_correction_range(beta_fast, beta_slow, dim, base, original_seq_len)
        smooth = 1 - linear_ramp_factor(low, high, dim // 2)
        freqs = freqs / factor * (1 - smooth) + freqs * smooth

    t = torch.arange(seqlen)
    freqs = torch.outer(t, freqs)
    freqs_cis = torch.polar(torch.ones_like(freqs), freqs)
    return freqs_cis


def apply_rotary_emb(x: torch.Tensor, freqs_cis: torch.Tensor, inverse: bool = False) -> torch.Tensor:
    """Applies rotary positional embeddings in-place. Uses conjugate for inverse (de-rotation)."""
    import ops
    return ops.rope_inplace(x, freqs_cis, inverse)


def apply_rotary_emb_torch(x: torch.Tensor, freqs_cis: torch.Tensor, inverse: bool = False) -> torch.Tensor:
    """Reference torch implementation (oracle for ops.rope_inplace)."""
    y = x
    x = torch.view_as_complex(x.float().unflatten(-1, (-1, 2)))
    if inverse:
        freqs_cis = freqs_cis.conj()
    if x.ndim == 3:
        freqs_cis = freqs_cis.view(1, x.size(1), x.size(-1))
    else:
        freqs_cis = freqs_cis.view(1, x.size(1), 1, x.size(-1))
    x = torch.view_as_real(x * freqs_cis).flatten(-2)
    y.copy_(x)
    return y


@lru_cache(1)
def get_window_topk_idxs(window_size: int, bsz: int, seqlen: int, start_pos: int):
    if start_pos >= window_size - 1:
        start_pos %= window_size
        matrix = torch.cat([torch.arange(start_pos + 1, window_size),  torch.arange(0, start_pos + 1)], dim=0)
    elif start_pos > 0:
        matrix = F.pad(torch.arange(start_pos + 1), (0, window_size - start_pos - 1), value=-1)
    else:
        base = torch.arange(seqlen).unsqueeze(1)
        matrix = (base - window_size + 1).clamp(0) + torch.arange(min(seqlen, window_size))
        matrix = torch.where(matrix > base, -1, matrix)
    return matrix.int().unsqueeze(0).expand(bsz, -1, -1).contiguous()


@lru_cache(1)
def get_flat_window_topk_idxs(window_size: int, bsz: int, start_pos: int):
    """Decode-step window indices into FLAT main_kv (absolute positions).
    Token order oldest->newest matches the ring variant, so the sparse_attn
    reduction order (and numerics) is identical."""
    lo = max(0, start_pos - window_size + 1)
    matrix = F.pad(torch.arange(lo, start_pos + 1), (0, window_size - (start_pos + 1 - lo)), value=-1)
    return matrix.int().view(1, 1, -1).expand(bsz, -1, -1).contiguous()


@lru_cache(2)
def get_compress_topk_idxs(ratio: int, bsz: int, seqlen: int, start_pos: int, offset: int):
    # Row s (absolute position p = start_pos + s) may attend the closed windows
    # 0 .. (p + 1) // ratio - 1.  Covers prefill (start_pos == 0), chunked prefill
    # (start_pos > 0, seqlen > 1) and decode (seqlen == 1) with one formula.
    matrix = torch.arange((start_pos + seqlen) // ratio).repeat(seqlen, 1)
    mask = matrix >= torch.arange(start_pos + 1, start_pos + seqlen + 1).unsqueeze(1) // ratio
    matrix = torch.where(mask, -1, matrix + offset)
    return matrix.int().unsqueeze(0).expand(bsz, -1, -1).contiguous()


class Compressor(nn.Module):
    """Compresses KV cache via learned gated pooling over `compress_ratio` consecutive tokens.
    When overlap=True (ratio==4), uses overlapping windows for smoother compression boundaries."""

    def __init__(self, args: ModelArgs, compress_ratio: int = 4, head_dim: int = 512, rotate: bool = False):
        super().__init__()
        self.dim = args.dim
        self.head_dim = head_dim
        self.rope_head_dim = args.rope_head_dim
        self.nope_head_dim = head_dim - args.rope_head_dim
        self.compress_ratio = compress_ratio
        self.overlap = compress_ratio == 4
        self.rotate = rotate
        coff = 1 + self.overlap

        self.ape = nn.Parameter(torch.empty(compress_ratio, coff * self.head_dim, dtype=torch.float32))
        # wkv and wgate in the checkpoint is stored in bf16, while the parameter here is stored in fp32 for convenient.
        # When overlap, the first half of dims is for overlapping compression, second half for normal.
        self.wkv = Linear(self.dim, coff * self.head_dim, dtype=torch.float32)
        self.wgate = Linear(self.dim, coff * self.head_dim, dtype=torch.float32)
        self.norm = RMSNorm(self.head_dim, args.norm_eps)
        self.freqs_cis: torch.Tensor = None

    def overlap_transform(self, tensor: torch.Tensor, value=0, prev=None):
        # tensor: [b,s,r,2d]; prev: [b,r,d] previous closed window or None (seq start -> value)
        b, s, _, _ = tensor.size()
        ratio, d = self.compress_ratio, self.head_dim
        new_tensor = tensor.new_full((b, s, 2 * ratio, d), value)
        new_tensor[:, :, ratio:] = tensor[:, :, :, d:]
        new_tensor[:, 1:, :ratio] = tensor[:, :-1, :, :d]
        if prev is not None and s > 0:
            new_tensor[:, 0, :ratio] = prev
        return new_tensor

    def proj(self, xf: torch.Tensor):
        """Per-token fp32 projections (wkv, wgate without ape) of xf [n, dim]."""
        if xf.dim() == 2 and xf.dtype == torch.float32 and xf.is_cuda and xf.is_contiguous():  # any M: skinny is batch-invariant, no cuBLAS fork
            from ops import _mod
            skinny = _mod().sgemm_skinny2_f32
            return skinny(xf, self.wkv.weight), skinny(xf, self.wgate.weight)
        return self.wkv(xf), self.wgate(xf)

    def forward(self, x: torch.Tensor, start_pos: int, prev: torch.Tensor = None):
        """Pure function. x: raw input of tokens [start_pos, start_pos + seqlen),
        start_pos r-aligned; returns the seqlen // r closed windows (None if < r).
        `prev` [1, r, dim] = raw x of the previous closed window (overlap only;
        None at sequence start). Decode closes a window by passing seqlen == r."""
        bsz, seqlen, _ = x.size()
        ratio, overlap, d, rd = self.compress_ratio, self.overlap, self.head_dim, self.rope_head_dim
        assert start_pos % ratio == 0, f"window start must be r-aligned, got {start_pos}"
        cutoff = seqlen - seqlen % ratio
        if cutoff < ratio:
            return None
        dtype = x.dtype
        x = x[:, :cutoff].float()
        # wkv/wgate are bf16-valued (checkpoint bf16, held in fp32) and x is a bf16 upcast, so
        # TF32 (10-bit mantissa) represents every operand exactly: products are identical to the
        # fp32 sgemm path, only the accumulation order changes. This routes the [T,4096]x[4096,N]
        # GEMMs onto tensor cores (fp32 sgemm was ~25% of 12k-token prefill; ~9x slower).
        _tf32 = torch.backends.cuda.matmul.allow_tf32
        torch.backends.cuda.matmul.allow_tf32 = True
        try:
            kv = self.wkv(x).unflatten(1, (-1, ratio))
            score = self.wgate(x).unflatten(1, (-1, ratio)) + self.ape
            if overlap:
                prev_kv = prev_score = None
                if prev is not None:
                    p = prev.float()
                    prev_kv = self.wkv(p)[:, :, :d]
                    prev_score = (self.wgate(p) + self.ape)[:, :, :d]
        finally:
            torch.backends.cuda.matmul.allow_tf32 = _tf32
        if overlap:
            kv = self.overlap_transform(kv, 0, prev_kv)
            score = self.overlap_transform(score, float("-inf"), prev_score)
        kv = (kv * score.softmax(dim=2)).sum(dim=2)
        kv = self.norm(kv.to(dtype))
        freqs_cis = self.freqs_cis[start_pos:start_pos + cutoff:ratio]
        apply_rotary_emb(kv[..., -rd:], freqs_cis)
        if self.rotate:
            kv = rotate_activation(kv)
            fp4_act_quant(kv, fp4_block_size, True)
        else:
            act_quant(kv[..., :-rd], 64, scale_fmt, scale_dtype, True)
        return kv


class Indexer(torch.nn.Module):
    """Selects top-k compressed KV positions for sparse attention via learned scoring.
    Has its own Compressor (with Hadamard rotation) to build compressed KV for scoring."""

    def __init__(self, args: ModelArgs, compress_ratio: int = 4):
        super().__init__()
        self.dim = args.dim
        self.n_heads = args.index_n_heads
        self.n_local_heads = args.index_n_heads // world_size
        self.head_dim = args.index_head_dim
        self.rope_head_dim = args.rope_head_dim
        self.index_topk = args.index_topk
        self.q_lora_rank = args.q_lora_rank
        self.wq_b = ColumnParallelLinear(self.q_lora_rank, self.n_heads * self.head_dim)
        self.weights_proj = ColumnParallelLinear(self.dim, self.n_heads, dtype=torch.bfloat16)
        self.softmax_scale = self.head_dim ** -0.5
        self.compress_ratio = compress_ratio

        self.compressor = Compressor(args, compress_ratio, self.head_dim, True)
        self.freqs_cis = None


class Attention(nn.Module):
    """Multi-head Latent Attention (MLA) with sliding window + optional KV compression.
    Uses low-rank Q projection (wq_a -> q_norm -> wq_b) and grouped low-rank O projection."""
    def __init__(self, layer_id: int, args: ModelArgs):
        super().__init__()
        self.layer_id = layer_id
        self.dim = args.dim
        self.n_heads = args.n_heads
        self.n_local_heads = args.n_heads // world_size
        self.q_lora_rank = args.q_lora_rank
        self.o_lora_rank = args.o_lora_rank
        self.head_dim = args.head_dim
        self.rope_head_dim = args.rope_head_dim
        self.nope_head_dim = args.head_dim - args.rope_head_dim
        self.n_groups = args.o_groups
        self.n_local_groups = self.n_groups // world_size
        self.window_size = args.window_size
        self.compress_ratio = args.compress_ratios[layer_id]
        self.eps = args.norm_eps

        self.attn_sink = nn.Parameter(torch.empty(self.n_local_heads, dtype=torch.float32))
        self.wq_a = Linear(self.dim, self.q_lora_rank)
        self.q_norm = RMSNorm(self.q_lora_rank, self.eps)
        self.wq_b = ColumnParallelLinear(self.q_lora_rank, self.n_heads * self.head_dim)
        self.wkv = Linear(self.dim, self.head_dim)
        self.kv_norm = RMSNorm(self.head_dim, self.eps)
        self.wo_a = ColumnParallelLinear(self.n_heads * self.head_dim // self.n_groups, self.n_groups * args.o_lora_rank, dtype=torch.bfloat16)
        self.wo_b = RowParallelLinear(self.n_groups * args.o_lora_rank, self.dim)
        self.softmax_scale = self.head_dim ** -0.5

        if self.compress_ratio:
            self.compressor = Compressor(args, self.compress_ratio, self.head_dim)
            if self.compress_ratio == 4:
                self.indexer = Indexer(args, self.compress_ratio)
            else:
                self.indexer = None

        # past (per-layer view into the model-wide SlotPool) is bound by Transformer.bind_pool
        self.past = None
        if self.compress_ratio:
            original_seq_len, rope_theta = args.original_seq_len, args.compress_rope_theta
        else:
            # disable YaRN and use base rope_theta in pure sliding-window attention
            original_seq_len, rope_theta = 0, args.rope_theta
        freqs_cis = precompute_freqs_cis(self.rope_head_dim, args.max_seq_len, original_seq_len,
                                         rope_theta, args.rope_factor, args.beta_fast, args.beta_slow)
        self.register_buffer("freqs_cis", freqs_cis, persistent=False)

    # forward is dispatched to the six reference ops in ops/attn_ref.py:
    #   {Base, Indexed, Compressed} x {prefill (start_pos == 0), decode (S == 1)}
    # Each op owns all past writes; see ops/attn_ref.py for the ABI.
    ratio: int = -1

    def bind_pool(self, pool: SlotPool) -> None:
        kw = dict(kv_dim=self.head_dim)
        if self.compress_ratio:
            kw["dim"] = self.dim
        self.past = pool.add_layer(self.layer_id, self.compress_ratio, **kw)
        if self.compress_ratio:
            for name, comp in (("ckv", self.compressor), ("ickv", getattr(self.indexer, "compressor", None))):
                if comp is not None:
                    comp.derived_name = name
                    self.past.add_derived(name, comp.proj, (1 + comp.overlap) * comp.head_dim)

    def forward(self, x: torch.Tensor, start_pos: int, slot: int = 0):
        from ops import attn_ref
        # prefill = whole sequence or a 128-aligned chunk (S > 1); decode = single token
        op = attn_ref.OPS[(self.ratio, "prefill" if (start_pos == 0 or x.size(1) > 1) else "decode")]
        return op(self, x, start_pos, slot)

    def forward_q(self, x: torch.Tensor, start_pos: int, slot: int = 0):
        """BnQ8 decode step (Q tokens at arbitrary start_pos), see docs/DECODE_BnQ8_CONTRACT.md."""
        if isinstance(start_pos, torch.Tensor):   # device-pos (graph-capturable) path
            from ops.attn_decode_g import OPS_G
            return OPS_G[self.ratio](self, x, start_pos, slot)
        from ops.attn_decode_q import OPS_Q
        return OPS_Q[self.ratio](self, x, start_pos, slot)

    def forward_qb(self, x: torch.Tensor, pos_list, slots):
        """Batched BnQ8 decode on the flat row stream x [1, B*Q, D] (device-pos path only);
        B == 1 runs the exact OPS_G op sequence, see ops.attn_decode_g.attn_decode_g_batch."""
        from ops.attn_decode_g import attn_decode_g_batch
        return attn_decode_g_batch(self, x, pos_list, slots)


class AttentionBase(Attention):
    """r=0: pure sliding-window MLA (layers 0,1). No compressor, no indexer.
    Past: flat LayerPast (main_kv only); window = main_kv[:, T-win:T]."""
    ratio = 0


class AttentionIndexed(Attention):
    """r=4: overlap compression + Indexer (even layers 2-42)."""
    ratio = 4


class AttentionCompressed(Attention):
    """r=128: coarse compression, positional index (odd layers 3-41)."""
    ratio = 128



ATTENTION_CLASSES = {0: AttentionBase, 4: AttentionIndexed, 128: AttentionCompressed}


class Gate(nn.Module):
    """MoE gating: computes expert routing scores and selects top-k experts.
    Supports hash-based routing (first n_hash_layers) where expert indices are
    predetermined per token ID, and score-based routing (remaining layers)."""
    def __init__(self, layer_id: int, args: ModelArgs):
        super().__init__()
        self.dim = args.dim
        self.topk = args.n_activated_experts
        self.score_func = args.score_func
        self.route_scale = args.route_scale
        self.hash = layer_id < args.n_hash_layers
        self.weight = nn.Parameter(torch.empty(args.n_routed_experts, args.dim))
        if self.hash:
            self.tid2eid = nn.Parameter(torch.empty(args.vocab_size, args.n_activated_experts, dtype=torch.int32), requires_grad=False)
            self.bias = None
        else:
            self.bias = nn.Parameter(torch.empty(args.n_routed_experts, dtype=torch.float32))


class Expert(nn.Module):
    """Single MoE expert: SwiGLU FFN (w1, w2, w3). Computation in float32 for stability."""
    def __init__(self, dim: int, inter_dim: int, dtype=None, swiglu_limit=0):
        super().__init__()
        self.w1 = ColumnParallelLinear(dim, inter_dim, dtype=dtype)
        # reduce=False: in NCCL mode each expert returns a partial sum;
        # MoE.forward merges routed+shared with a single all_reduce.
        self.w2 = RowParallelLinear(inter_dim, dim, dtype=dtype, reduce=False)
        self.w3 = ColumnParallelLinear(dim, inter_dim, dtype=dtype)
        self.swiglu_limit = swiglu_limit


class MoE(nn.Module):
    """Mixture-of-Experts: gate routes each token to top-k routed experts + 1 shared expert.
    Experts are sharded across TP ranks; each rank handles n_routed_experts // world_size experts."""
    def __init__(self, layer_id: int, args: ModelArgs):
        super().__init__()
        self.layer_id = layer_id
        self.dim = args.dim
        assert args.n_routed_experts % world_size == 0, f"Number of experts must be divisible by world size (world_size={world_size})"
        self.n_routed_experts = args.n_routed_experts
        self.n_local_experts = args.n_routed_experts // world_size
        self.n_activated_experts = args.n_activated_experts
        # NCCL mode uses intra-expert TP (banks are TP-sharded per expert),
        # so every rank iterates all experts; partial sums merge in the final all_reduce.
        self.experts_start_idx = 0
        self.experts_end_idx = self.n_routed_experts
        self.gate = Gate(layer_id, args)
        expert_dtype = torch.float4_e2m1fn_x2 if args.expert_dtype == "fp4" else None
        self.experts = nn.ModuleList([Expert(args.dim, args.moe_inter_dim, dtype=expert_dtype, swiglu_limit=args.swiglu_limit) if self.experts_start_idx <= i < self.experts_end_idx else None
                                       for i in range(self.n_routed_experts)])
        assert args.n_shared_experts == 1
        self.shared_experts = Expert(args.dim, args.moe_inter_dim, swiglu_limit=args.swiglu_limit)


class Block(nn.Module):
    """Transformer block with Hyper-Connections (HC) mixing.
    Instead of a simple residual, HC maintains `hc_mult` copies of the hidden state.
    hc_pre: reduces hc copies -> 1 via learned weighted sum (pre-weights from Sinkhorn).
    hc_post: expands 1 -> hc copies via learned post-weights + combination matrix."""
    attention_cls = Attention

    def __init__(self, layer_id: int, args: ModelArgs):
        super().__init__()
        self.layer_id = layer_id
        self.norm_eps = args.norm_eps
        if self.attention_cls is Attention:
            attn_cls = ATTENTION_CLASSES[args.compress_ratios[layer_id]]
        else:
            attn_cls = self.attention_cls
        self.attn = attn_cls(layer_id, args)
        self.ffn = MoE(layer_id, args)
        self.attn_norm = RMSNorm(args.dim, self.norm_eps)
        self.ffn_norm = RMSNorm(args.dim, self.norm_eps)
        self.hc_mult = hc_mult = args.hc_mult
        self.hc_sinkhorn_iters = args.hc_sinkhorn_iters
        self.hc_eps = args.hc_eps
        assert self.hc_eps == self.norm_eps, "fused hc kernel shares one eps"
        mix_hc = (2 + hc_mult) * hc_mult
        hc_dim = hc_mult * args.dim
        with set_dtype(torch.float32):
            self.hc_attn_fn = nn.Parameter(torch.empty(mix_hc, hc_dim))
            self.hc_ffn_fn = nn.Parameter(torch.empty(mix_hc, hc_dim))
            self.hc_attn_base = nn.Parameter(torch.empty(mix_hc))
            self.hc_ffn_base = nn.Parameter(torch.empty(mix_hc))
            self.hc_attn_scale = nn.Parameter(torch.empty(3))
            self.hc_ffn_scale = nn.Parameter(torch.empty(3))

    def hc_post(self, x: torch.Tensor, residual: torch.Tensor, post: torch.Tensor, comb: torch.Tensor):
        # x: [b,s,d], residual: [b,s,hc,d], post: [b,s,hc], comb: [b,s,hc,hc], y: [b,s,hc,d]
        from ops import hc_post
        return hc_post(x, residual, post, comb)

    def forward(self, x: torch.Tensor, start_pos: int, input_ids: Optional[torch.Tensor], *attn_args,
                q_decode: bool = False) -> torch.Tensor:
        residual = x
        from ops import hc_pre_norm
        # fused hc_pre + attn_norm (kernel shares one eps: norm_eps == hc_eps asserted in __init__)
        x, post, comb = hc_pre_norm(x, self.hc_attn_fn, self.hc_attn_scale, self.hc_attn_base,
                                    self.attn_norm.weight, self.attn_norm.eps)
        x = (self.attn.forward_q if q_decode else self.attn)(x, start_pos, *attn_args)
        x = self.hc_post(x, residual, post, comb)

        return self.fused_ffn(x, input_ids, q_decode=q_decode)

    def forward_qb(self, x: torch.Tensor, pos_list, slots, input_ids: torch.Tensor) -> torch.Tensor:
        """Batched decode block. Hidden is one flat [1, B*Q, hc, d] token stream:
        attention runs per row (KV lives in a per-slot ring/page table, so rows cannot
        merge), while hc_pre/hc_post/MoE stay token-wise batched -- the MoE weights are
        therefore read once for all B rows, which is where the batching win comes from."""
        residual = x
        from ops import hc_pre_norm
        x, post, comb = hc_pre_norm(x, self.hc_attn_fn, self.hc_attn_scale, self.hc_attn_base,
                                    self.attn_norm.weight, self.attn_norm.eps)
        # token-wise attention stages (q/kv/o projections + the wo_b all_reduce) run once
        # on the flat [1, B*Q] stream; only the slot-bound core (KV write / compress /
        # indexer / sparse attention) runs per row inside attn.forward_qb.
        x = self.attn.forward_qb(x, pos_list, slots)
        x = self.hc_post(x, residual, post, comb)
        return self.fused_ffn(x, input_ids, q_decode=True)

    def fused_ffn(self, x: torch.Tensor, input_ids: Optional[torch.Tensor], q_decode: bool = False) -> torch.Tensor:
        """Fused MoE: hc_pre + ffn_norm + gate + routed fp4 + shared bf16 in one kernel.
        q_decode -> decode variant (no D2H sync, graph-capturable)."""
        from ops import moe_rank_fused_prefill_fp4, moe_rank_fused_fp4
        moe_op = moe_rank_fused_fp4 if q_decode else moe_rank_fused_prefill_fp4
        residual = x
        b, s, hc, d = x.shape
        xf = x.reshape(b * s, hc, d)
        tok = input_ids.flatten() if input_ids is not None else None
        m = self.ffn
        gw, gb, t2e = m.fused_gate

        def _call(r):
            g = (lambda t: t) if r is None else (lambda t: t[r])
            W = g(gw)
            dev = W.device
            if t2e is not None:
                ids_pre = g(t2e)[tok.to(dev)].long()
                rbias = W[:0]
            else:
                ids_pre = W.new_empty((0,), dtype=torch.long)
                rbias = g(gb)
            (w1w, w1s), (w3w, w3s), (w2w, w2s) = m.fused_bank
            s1, s3, s2 = m.fused_shared  # bf16, dequantized at bind time
            return moe_op(
                xf.to(dev), self.hc_ffn_fn.to(dev), self.hc_ffn_scale.to(dev),
                self.hc_ffn_base.to(dev), g(m.fused_norm),
                W, rbias, ids_pre,
                g(w1w), g(w1s), g(w3w), g(w3s), g(w2w), g(w2s),
                g(s1), g(s3), g(s2), self.norm_eps)

        if isinstance(gw, list):  # loop-TP8: sum partials in fp32 (matches all_reduce)
            post = comb = y = None
            for r in range(len(gw)):
                p, c, yr, sr, _ = _call(r)
                part = (yr.float() + sr.float()).to(x.device)
                if y is None:
                    post, comb, y = p.to(x.device), c.to(x.device), part
                else:
                    y += part
        else:  # NCCL: local rank kernel + all_reduce
            post, comb, yr, sr, _ = _call(None)
            if yr.dtype == torch.bfloat16 and sr.dtype == torch.bfloat16 \
                    and yr.is_contiguous() and sr.is_contiguous():
                # one fused kernel instead of two casts + one add (bit-identical)
                from ops import add2_bf16_f32
                y = torch.empty(yr.shape, dtype=torch.float32, device=yr.device)
                add2_bf16_f32(yr, sr, y)
            else:
                y = yr.float() + sr.float()
            from ops import peer_ar
            T = y.shape[0]
            if (not q_decode and dist.is_initialized() and dist.get_world_size() > 1
                    and T % dist.get_world_size() == 0 and T >= 8 * dist.get_world_size()):
                # prefill: fp32 reduce_scatter -> local bf16 round -> bf16 all_gather.
                # Same fp32 reduction then bf16 round as AR+hc_post f32 branch; gather phase
                # moves half the bytes (ring AR = RS+AG). Not bit-same: RS reduction order
                # may differ from AR's (1-ulp bf16 flips on ~5e-5 of elements, tf gate covers).
                ws = dist.get_world_size()
                part = torch.empty(T // ws, d, dtype=torch.float32, device=y.device)
                dist.reduce_scatter_tensor(part, y)
                yb = torch.empty(T, d, dtype=torch.bfloat16, device=y.device)
                dist.all_gather_into_tensor(yb, part.to(torch.bfloat16))
                y = yb
            else:
                peer_ar.all_reduce(y)
        y = y.view(b, s, d)   # f32 (decode) -> hc_post f32 branch rounds in-kernel; bf16 (prefill RS+AG path)
        post = post.view(b, s, hc)
        comb = comb.view(b, s, hc, hc)
        return self.hc_post(y, residual, post, comb)

    def hc_head(self, x: torch.Tensor, hc_fn: torch.Tensor, hc_scale: torch.Tensor, hc_base: torch.Tensor):
        shape, dtype = x.size(), x.dtype
        x = x.flatten(2).float()
        rsqrt = torch.rsqrt(x.square().mean(-1, keepdim=True) + self.norm_eps)
        mixes = F.linear(x, hc_fn) * rsqrt
        pre = torch.sigmoid(mixes * hc_scale + hc_base) + self.hc_eps
        y = torch.sum(pre.unsqueeze(-1) * x.view(shape), dim=2)
        return y.to(dtype)


class ParallelHead(nn.Module):
    """Loop-TP8: weight is list of shards [vocab/8, dim] (bf16 in ckpt); fp32 logits, concat on vocab."""
    def __init__(self, vocab_size: int, dim: int, norm_eps: float = 1e-6, hc_eps: float = 1e-6):
        super().__init__()
        self.vocab_size = vocab_size
        self.dim = dim
        self.norm_eps = norm_eps
        self.hc_eps = hc_eps
        self.weight = None  # bound by loader: list[Tensor]

    def forward(self, x: torch.Tensor, full_logits=False):
        # x: [b,s,hc,d]
        if not full_logits:
            x = x[:, -1]
        if not isinstance(self.weight, list):  # NCCL: local shard + all_gather on vocab dim
            local = F.linear(x.to(self.weight.dtype), self.weight).float().contiguous()  # bf16 GEMM, fp32 out (same as broken decode_dsv4_bn)
            outs = [torch.empty_like(local) for _ in range(world_size)]
            dist.all_gather(outs, local)
            return torch.cat(outs, dim=-1)
        outs = [F.linear(x.float().to(w.device), w.float()).to(x.device) for w in self.weight]
        return torch.cat(outs, dim=-1)


class DSparkAttention(Attention):
    """MTP attention on the canonical flat LayerPast (main_kv[:, pos]); window = last `window_size` positions.
    Any start_pos may write (chunked prefill / cold-KV friendly); no ring, no module-level cache."""

    def write_kv(self, main_x: torch.Tensor, start_pos: int, slot: int = 0) -> None:
        """Write-only path: draft main_kv for main_x [1, n, .] at [start_pos, start_pos+n), any n."""
        rd = self.rope_head_dim
        main_kv = self.kv_norm(self.wkv(main_x))
        apply_rotary_emb(main_kv[..., -rd:], self.freqs_cis[start_pos:start_pos + main_x.size(1)])
        act_quant(main_kv[..., :-rd], 64, scale_fmt, scale_dtype, True)
        self.past.write_kv(slot, start_pos, main_kv[0])

    def forward(self, x: torch.Tensor, start_pos: int, main_x: torch.Tensor, slot: int = 0):
        assert self.compress_ratio == 0
        bsz, seqlen, _ = main_x.size()
        assert bsz == 1, bsz
        win = self.window_size
        rd = self.rope_head_dim

        main_freqs_cis = self.freqs_cis[start_pos:start_pos+seqlen]
        main_kv = self.kv_norm(self.wkv(main_x))
        apply_rotary_emb(main_kv[..., -rd:], main_freqs_cis)
        act_quant(main_kv[..., :-rd], 64, scale_fmt, scale_dtype, True)

        self.past.write_kv(slot, start_pos, main_kv[0])
        if start_pos == 0:
            return x

        bsz, block_size, _ = x.size()
        freqs_cis = self.freqs_cis[start_pos+seqlen:start_pos+seqlen+block_size]

        q = self.q_norm(self.wq_a(x))
        q = self.wq_b(q).unflatten(-1, (self.n_local_heads, self.head_dim))
        q *= torch.rsqrt(q.square().mean(-1, keepdim=True) + self.eps)
        apply_rotary_emb(q[..., -rd:], freqs_cis)
        kv = self.kv_norm(self.wkv(x))
        apply_rotary_emb(kv[..., -rd:], freqs_cis)
        act_quant(kv[..., :-rd], 64, scale_fmt, scale_dtype, True)

        assert seqlen == 1, seqlen
        lo = max(0, start_pos + 1 - win)
        ctx = self.past.kv(slot, lo, start_pos + 1).unsqueeze(0)
        kv = torch.cat([ctx, kv], dim=1)
        topk_idxs = torch.arange(kv.size(1), device=kv.device, dtype=torch.int32).view(1, 1, -1).expand(bsz, block_size, -1)
        o = sparse_attn(q, kv, self.attn_sink, topk_idxs, self.softmax_scale)
        apply_rotary_emb(o[..., -rd:], freqs_cis, True)

        o = o.view(bsz, block_size, self.n_local_groups, -1)
        from ops import wo_a_grouped
        o = wo_a_grouped(o, self.wo_a.weight)
        x = self.wo_b(o.flatten(2))
        return x


    def forward_q(self, x: torch.Tensor, pos_t: torch.Tensor, main_x: torch.Tensor, slot: int = 0,
                  main_pos_t: torch.Tensor = None):
        """CUDA-graph-capturable decode step: pos_t int64 device [1] = position of the query anchor token.
        main_x [1, S] rows are written to main_kv at main_pos_t [S] (default pos_t + arange(S));
        the draft block queries positions pos_t+1.. over a fixed `window_size` context ending at pos_t
        (invalid rows masked with -1)."""
        assert self.compress_ratio == 0
        bsz, seqlen, _ = main_x.size()
        assert bsz == 1, main_x.shape
        if main_pos_t is None:
            main_pos_t = pos_t + torch.arange(seqlen, device=pos_t.device)
        win = self.window_size
        rd = self.rope_head_dim
        ring = self.past.ring
        dev = pos_t.device

        main_freqs_cis = self.freqs_cis.index_select(0, main_pos_t)
        main_kv = self.kv_norm(self.wkv(main_x))
        apply_rotary_emb(main_kv[..., -rd:], main_freqs_cis)
        act_quant(main_kv[..., :-rd], 64, scale_fmt, scale_dtype, True)
        self.past.main_kv[slot].index_copy_(0, main_pos_t % ring, main_kv[0].to(self.past.main_kv.dtype))

        bsz, block_size, _ = x.size()
        freqs_cis = self.freqs_cis.index_select(0, pos_t + 1 + torch.arange(block_size, device=dev))

        q = self.q_norm(self.wq_a(x))
        q = self.wq_b(q).unflatten(-1, (self.n_local_heads, self.head_dim))
        q *= torch.rsqrt(q.square().mean(-1, keepdim=True) + self.eps)
        apply_rotary_emb(q[..., -rd:], freqs_cis)
        kv = self.kv_norm(self.wkv(x))
        apply_rotary_emb(kv[..., -rd:], freqs_cis)
        act_quant(kv[..., :-rd], 64, scale_fmt, scale_dtype, True)

        wpos = pos_t + 1 - win + torch.arange(win, device=dev)               # abs positions of window
        ctx = self.past.main_kv[slot].index_select(0, wpos.clamp_min(0) % ring).unsqueeze(0)
        kv = torch.cat([ctx, kv], dim=1)
        idx = torch.arange(win + block_size, device=dev, dtype=torch.int32)
        valid = torch.cat([wpos >= 0, torch.ones(block_size, dtype=torch.bool, device=dev)])
        topk_idxs = torch.where(valid, idx, idx.new_full((), -1)).view(1, 1, -1).expand(bsz, block_size, -1)
        o = sparse_attn(q, kv, self.attn_sink, topk_idxs, self.softmax_scale)
        apply_rotary_emb(o[..., -rd:], freqs_cis, True)

        o = o.view(bsz, block_size, self.n_local_groups, -1)
        from ops import wo_a_grouped
        o = wo_a_grouped(o, self.wo_a.weight)
        x = self.wo_b(o.flatten(2))
        return x


    def forward_qb(self, x: torch.Tensor, pos_list, slots, main_x: torch.Tensor, main_pos_list):
        """Batched (B rows) variant of forward_q -- A4 of amdahl_b_report.
        x [B, block_size, d], main_x [B, S, D]; pos_list / main_pos_list: per-row int64
        device tensors ([1] and [S]); slots list[int].
        Token-wise stages (wkv/wq/rope/act_quant, wo_a, wo_b + its all_reduce) run ONCE on
        the flat [1, B*n] stream so the projection weights are read once and the wo_b
        all_reduce is 1 collective instead of B.  Only the slot-bound part (main_kv write,
        window read, sparse_attn) runs per row.  B == 1 follows forward_q line by line."""
        assert self.compress_ratio == 0
        B, S, _ = main_x.size()
        assert len(slots) == B == len(pos_list) == len(main_pos_list), (B, len(slots))
        win = self.window_size
        rd = self.rope_head_dim
        ring = self.past.ring
        dev = main_x.device
        main_pos_flat = main_pos_list[0] if B == 1 else torch.cat(main_pos_list)          # [B*S]

        main_freqs_cis = self.freqs_cis.index_select(0, main_pos_flat)
        main_kv = self.kv_norm(self.wkv(main_x)).view(1, B * S, -1)                        # flat stream
        apply_rotary_emb(main_kv[..., -rd:], main_freqs_cis)
        act_quant(main_kv[..., :-rd], 64, scale_fmt, scale_dtype, True)
        main_kv = main_kv.view(B, S, -1).to(self.past.main_kv.dtype)
        for b in range(B):
            self.past.main_kv[slots[b]].index_copy_(0, main_pos_list[b] % ring, main_kv[b])

        _, block_size, _ = x.size()
        arb = torch.arange(block_size, device=dev)
        qpos_list = [pos_list[b] + 1 + arb for b in range(B)]                              # [bs] each
        freqs_cis = self.freqs_cis.index_select(0, qpos_list[0] if B == 1 else torch.cat(qpos_list))

        q = self.q_norm(self.wq_a(x))
        q = self.wq_b(q).unflatten(-1, (self.n_local_heads, self.head_dim)).view(1, B * block_size, self.n_local_heads, self.head_dim)
        q *= torch.rsqrt(q.square().mean(-1, keepdim=True) + self.eps)
        apply_rotary_emb(q[..., -rd:], freqs_cis)
        kv = self.kv_norm(self.wkv(x)).view(1, B * block_size, -1)
        apply_rotary_emb(kv[..., -rd:], freqs_cis)
        act_quant(kv[..., :-rd], 64, scale_fmt, scale_dtype, True)
        q = q.view(B, block_size, self.n_local_heads, self.head_dim)
        kv = kv.view(B, block_size, -1)

        idx = torch.arange(win + block_size, device=dev, dtype=torch.int32)
        ones = torch.ones(block_size, dtype=torch.bool, device=dev)
        arw = torch.arange(win, device=dev)
        os_ = []
        for b in range(B):                                                                 # slot-bound core
            wpos = pos_list[b] + 1 - win + arw
            ctx = self.past.main_kv[slots[b]].index_select(0, wpos.clamp_min(0) % ring).unsqueeze(0)
            kvb = torch.cat([ctx, kv[b:b + 1]], dim=1)
            valid = torch.cat([wpos >= 0, ones])
            topk_idxs = torch.where(valid, idx, idx.new_full((), -1)).view(1, 1, -1).expand(1, block_size, -1)
            os_.append(sparse_attn(q[b:b + 1], kvb, self.attn_sink, topk_idxs, self.softmax_scale))
        o = (os_[0] if B == 1 else torch.cat(os_, dim=0)).view(1, B * block_size, self.n_local_heads, self.head_dim)
        apply_rotary_emb(o[..., -rd:], freqs_cis, True)

        o = o.view(B, block_size, self.n_local_groups, -1)
        from ops import wo_a_grouped
        o = wo_a_grouped(o, self.wo_a.weight)
        x = self.wo_b(o.flatten(2))
        return x


class DSparkMarkovHead(nn.Module):
    def __init__(self, vocab_size: int, dspark_markov_rank: int):
        super().__init__()
        self.markov_w1 = ParallelEmbedding(vocab_size, dspark_markov_rank)
        self.markov_w2 = ParallelHead(vocab_size, dspark_markov_rank)

    def forward(self, token_ids: torch.Tensor) -> torch.Tensor:
        embed = self.markov_w1(token_ids)
        logits = self.markov_w2(embed, full_logits=True)
        return logits, embed


class DSparkConfidenceHead(nn.Module):
    def __init__(self, input_dim: int):
        super().__init__()
        # proj in the checkpoint is stored in bf16, while the parameter here is stored in fp32 for fp32 confidence score.
        self.proj = Linear(input_dim, 1, dtype=torch.float32)

    def forward(self, hidden: torch.Tensor, markov_embed: torch.Tensor):
        hidden = torch.cat([hidden, markov_embed], dim=-1)
        return self.proj(hidden.float()).squeeze(-1)


class DSparkBlock(Block):
    """DSpark stage stored under the mtp.* checkpoint namespace."""
    attention_cls = DSparkAttention

    def __init__(self, layer_id: int, args: ModelArgs):
        super().__init__(layer_id, args)
        self.dim = args.dim
        stage_id = layer_id - args.n_layers
        self.block_size = args.dspark_block_size
        self.noise_token_id = args.dspark_noise_token_id
        self.temperature = args.temperature
        hc_dim = self.hc_mult * args.dim
        if stage_id == 0:
            assert len(args.dspark_target_layer_ids) > 0, "DSpark needs target layers"
            self.main_proj = Linear(args.dim * len(args.dspark_target_layer_ids), args.dim)
            self.main_norm = RMSNorm(args.dim, args.norm_eps)
        if stage_id == args.n_mtp_layers - 1:
            self.norm = RMSNorm(args.dim, args.norm_eps)
            self.markov_head = DSparkMarkovHead(args.vocab_size, args.dspark_markov_rank)
            self.confidence_head = DSparkConfidenceHead(args.dim + args.dspark_markov_rank)
            with set_dtype(torch.float32):
                self.hc_head_fn = nn.Parameter(torch.empty(self.hc_mult, hc_dim))
                self.hc_head_base = nn.Parameter(torch.empty(self.hc_mult))
                self.hc_head_scale = nn.Parameter(torch.empty(1))
        self.embed: ParallelEmbedding = None
        self.head: ParallelHead = None

    def forward(self, x: torch.Tensor, start_pos: int, input_ids: torch.Tensor, main_x: torch.Tensor, slot: int = 0) -> torch.Tensor:
        if start_pos > 0:
            return super().forward(x, start_pos, input_ids, main_x, slot)
        # only compute KV cache in prefill stage
        return self.attn(x, start_pos, main_x, slot)

    def forward_q(self, x: torch.Tensor, pos_t: torch.Tensor, input_ids: torch.Tensor, main_x: torch.Tensor, slot: int = 0,
                  main_pos_t: torch.Tensor = None) -> torch.Tensor:
        """Graph-capturable decode (pos > 0 by construction; pos_t device tensor)."""
        return Block.forward(self, x, pos_t, input_ids, main_x, slot, main_pos_t, q_decode=True)

    def forward_qb(self, x: torch.Tensor, pos_list, slots, input_ids: torch.Tensor, main_x: torch.Tensor,
                   main_pos_list) -> torch.Tensor:
        """Batched decode (A4): x [B, block_size, hc, d] for B rows at once.  hc_pre/hc_post/
        fused_ffn are token-wise and already handle the leading B dim; only the attention
        needs the per-row slot-bound split (DSparkAttention.forward_qb)."""
        residual = x
        from ops import hc_pre_norm
        x, post, comb = hc_pre_norm(x, self.hc_attn_fn, self.hc_attn_scale, self.hc_attn_base,
                                    self.attn_norm.weight, self.attn_norm.eps)
        x = self.attn.forward_qb(x, pos_list, slots, main_x, main_pos_list)
        x = self.hc_post(x, residual, post, comb)
        return self.fused_ffn(x, input_ids, q_decode=True)

    def forward_embed(self, main_hidden: torch.Tensor, input_ids: torch.Tensor):
        assert self.embed is not None
        main_x = self.main_norm(self.main_proj(main_hidden))
        draft_input_ids = input_ids.new_full([input_ids.size(0), self.block_size], self.noise_token_id)
        draft_input_ids[:, 0] = input_ids
        x = self.embed(draft_input_ids)
        x = x.unsqueeze(2).repeat(1, 1, self.hc_mult, 1)
        return x, main_x

    def forward_head(self, x: torch.Tensor, input_ids: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        assert self.head is not None
        x = self.hc_head(x, self.hc_head_fn, self.hc_head_scale, self.hc_head_base)
        logits = self.head(self.norm(x), full_logits=True)
        output_ids = input_ids.new_empty(input_ids.size(0), self.block_size + 1)
        output_ids[:, 0] = input_ids
        markov_embeds = []
        for i in range(self.block_size):
            logits_bias, markov_embed = self.markov_head(output_ids[:, i])
            logits[:, i].add_(logits_bias)
            markov_embeds.append(markov_embed)
            output_ids[:, i + 1] = sample(logits[:, i], self.temperature)
        markov_embed = torch.stack(markov_embeds, dim=1)
        confidence = self.confidence_head(x, markov_embed)
        return output_ids, logits, confidence


class Transformer(nn.Module):
    """Full DeepSeek-V4 model: embed -> HC-expand -> N blocks -> HC-head -> logits.
    Sets global state (world_size, rank, default_dtype, scale_fmt, scale_dtype) in __init__."""
    def __init__(self, args: ModelArgs):
        global world_size, rank, default_dtype, scale_fmt, scale_dtype
        world_size = dist.get_world_size() if dist.is_initialized() else 1
        rank = dist.get_rank() if dist.is_initialized() else 0
        default_dtype = torch.float8_e4m3fn if args.dtype == "fp8" else torch.bfloat16
        scale_fmt = "ue8m0" if args.scale_dtype == "fp8" else args.scale_fmt
        scale_dtype = torch.float8_e8m0fnu if args.scale_dtype == "fp8" else torch.float32
        super().__init__()
        self.max_seq_len = args.max_seq_len
        self.temperature = args.temperature
        self.norm_eps = args.norm_eps
        self.hc_eps = args.hc_eps
        self.embed = ParallelEmbedding(args.vocab_size, args.dim)
        self.layers = torch.nn.ModuleList()
        for layer_id in range(args.n_layers):
            self.layers.append(Block(layer_id, args))
        self.norm = RMSNorm(args.dim, self.norm_eps)
        self.head = ParallelHead(args.vocab_size, args.dim, self.norm_eps, self.hc_eps)
        self.mtp = torch.nn.ModuleList()
        self.target_layer_ids = args.dspark_target_layer_ids
        if args.dspark_block_size:
            for layer_id in range(args.n_mtp_layers):
                self.mtp.append(DSparkBlock(args.n_layers + layer_id, args))
                self.mtp[-1].embed = self.embed
                self.mtp[-1].head = self.head
        self.hc_mult = hc_mult = args.hc_mult
        hc_dim = hc_mult * args.dim
        with set_dtype(torch.float32):
            self.hc_head_fn = nn.Parameter(torch.empty(hc_mult, hc_dim))
            self.hc_head_base = nn.Parameter(torch.empty(hc_mult))
            self.hc_head_scale = nn.Parameter(torch.empty(1))
        # one SlotPool per model: n_slots sequences, shared page table, every layer's past
        self.pool = SlotPool(args.max_batch_size, args.max_seq_len,
                             pool_tokens=args.pool_tokens,
                             device=torch.device('cuda', torch.cuda.current_device()))
        for layer in list(self.layers) + list(self.mtp):
            layer.attn.bind_pool(self.pool)

    def _set_pos(self, slot: int, pos: int) -> None:
        self.pool.ensure(slot, pos)
        self.pool.pos[slot] = pos
        self.pool.pos_dev[slot] = pos

    @torch.inference_mode()
    def forward(self, input_ids: torch.Tensor, start_pos: int = 0, full_logits: bool = False, slot: int = 0):
        assert input_ids.size(0) == 1, input_ids.shape
        self._set_pos(slot, start_pos + input_ids.size(1))
        h = self.embed(input_ids)
        # Expand to hc_mult copies for Hyper-Connections
        h = h.unsqueeze(2).repeat(1, 1, self.hc_mult, 1)
        main_hiddens = []
        for i, layer in enumerate(self.layers):
            h = layer(h, start_pos, input_ids, slot)
            if i in self.target_layer_ids:
                main_hiddens.append(h.mean(dim=2))
        h = layer.hc_head(h, self.hc_head_fn, self.hc_head_scale, self.hc_head_base)
        logits = self.head(self.norm(h), full_logits=full_logits)
        output_ids = sample(logits, self.temperature)
        main_hidden = torch.cat(main_hiddens, dim=-1) if main_hiddens else None
        return output_ids, logits, main_hidden

    @torch.inference_mode()
    def forward_q(self, input_ids: torch.Tensor, start_pos: int, slot: int = 0):
        """BnQ8 verify step: input_ids [1, Q] at arbitrary start_pos > 0. Returns full
        logits [1, Q, V] (row 0 == single-token decode of start_pos) and main_hidden."""
        assert input_ids.size(0) == 1 and start_pos > 0, input_ids.shape
        self._set_pos(slot, start_pos + input_ids.size(1))
        h = self.embed(input_ids)
        h = h.unsqueeze(2).repeat(1, 1, self.hc_mult, 1)
        main_hiddens = []
        for i, layer in enumerate(self.layers):
            h = layer(h, start_pos, input_ids, slot, q_decode=True)
            if i in self.target_layer_ids:
                main_hiddens.append(h.mean(dim=2))
        h = layer.hc_head(h, self.hc_head_fn, self.hc_head_scale, self.hc_head_base)
        logits = self.head(self.norm(h), full_logits=True)
        main_hidden = torch.cat(main_hiddens, dim=-1) if main_hiddens else None
        return logits, main_hidden

    @torch.inference_mode()
    def forward_q_g(self, input_ids: torch.Tensor, pos_t: torch.Tensor, slot: int = 0):
        """CUDA-graph-capturable BnQ8 step: pos_t is an int64 device tensor [1]; no host
        sync. Caller must pool.ensure(slot, max_pos + Q) beforehand."""
        from ops.attn_decode_g import step_ctx_reset; step_ctx_reset()
        q = input_ids.size(1)
        self.pool.pos_dev[slot:slot + 1].copy_((pos_t + q).to(torch.int32))
        h = self.embed(input_ids)
        h = h.unsqueeze(2).repeat(1, 1, self.hc_mult, 1)
        main_hiddens = []
        for i, layer in enumerate(self.layers):
            h = layer(h, pos_t, input_ids, slot, q_decode=True)
            if i in self.target_layer_ids:
                main_hiddens.append(h.mean(dim=2))
        h = layer.hc_head(h, self.hc_head_fn, self.hc_head_scale, self.hc_head_base)
        logits = self.head(self.norm(h), full_logits=True)
        main_hidden = torch.cat(main_hiddens, dim=-1) if main_hiddens else None
        return logits, main_hidden

    @torch.inference_mode()
    def forward_q_g_batch(self, input_ids: torch.Tensor, pos_t: torch.Tensor, slots):
        """Batched CUDA-graph-capturable BnQ8 step (B rows x Q tokens).

        input_ids [B, Q]; pos_t int64 device [B] (row b's anchor position); slots list[int].
        Rows are flattened into a single [1, B*Q] stream so every token-wise stage (embed,
        hc, MoE, head) is shared, while attention is dispatched per row against its own
        slot. B == 1 is bit-identical to forward_q_g. No host sync; caller must have done
        pool.ensure(slot, pos + Q) for every slot beforehand.
        Returns logits [B, Q, V], main_hidden [B, Q, D] (or None)."""
        from ops.attn_decode_g import step_ctx_reset; step_ctx_reset()
        B, Q = int(input_ids.size(0)), int(input_ids.size(1))
        assert len(slots) == B and pos_t.numel() == B, (input_ids.shape, len(slots), pos_t.shape)
        flat_ids = input_ids.reshape(1, B * Q)
        pos_list = [pos_t[b:b + 1] for b in range(B)]        # distinct data_ptr -> distinct _CTX key
        for b, slot in enumerate(slots):
            self.pool.pos_dev[slot:slot + 1].copy_((pos_list[b] + Q).to(torch.int32))
        h = self.embed(flat_ids)
        h = h.unsqueeze(2).repeat(1, 1, self.hc_mult, 1)
        main_hiddens = []
        for i, layer in enumerate(self.layers):
            h = layer.forward_qb(h, pos_list, slots, flat_ids)
            if i in self.target_layer_ids:
                main_hiddens.append(h.mean(dim=2))
        h = layer.hc_head(h, self.hc_head_fn, self.hc_head_scale, self.hc_head_base)
        logits = self.head(self.norm(h), full_logits=True).reshape(B, Q, -1)
        main_hidden = torch.cat(main_hiddens, dim=-1).reshape(B, Q, -1) if main_hiddens else None
        return logits, main_hidden

    @torch.inference_mode()
    def write_draft_kv(self, main_hidden: torch.Tensor, start_pos: int, slot: int = 0) -> None:
        """Chunked-prefill companion of forward_spec(start_pos=0): only writes draft main_kv for
        main_hidden [1, n, .] at [start_pos, start_pos+n) (mirrors forward_embed's main_x)."""
        self.pool.ensure(slot, start_pos + main_hidden.size(1))
        m0 = self.mtp[0]
        main_x = m0.main_norm(m0.main_proj(main_hidden))
        for layer in self.mtp:
            layer.attn.write_kv(main_x, start_pos, slot)

    @torch.inference_mode()
    def forward_spec(self, input_ids: torch.Tensor, main_hidden: torch.Tensor, start_pos: int = 0, slot: int = 0):
        self.pool.ensure(slot, start_pos + input_ids.shape[-1])
        h, main_x = self.mtp[0].forward_embed(main_hidden, input_ids)
        for layer in self.mtp:
            h = layer(h, start_pos, input_ids, main_x, slot)
        if start_pos == 0:
            return
        output_ids, logits, confidence = self.mtp[-1].forward_head(h, input_ids)
        return output_ids, logits, confidence

    @torch.inference_mode()
    def forward_spec_g(self, input_ids: torch.Tensor, main_hidden: torch.Tensor, pos_t: torch.Tensor, slot: int = 0):
        """CUDA-graph-capturable DSpark draft step: pos_t int64 device [1]; no host sync.
        Caller must pool.ensure(slot, max_pos + block_size + 1) beforehand."""
        from ops.attn_decode_g import step_ctx_reset; step_ctx_reset()
        h, main_x = self.mtp[0].forward_embed(main_hidden, input_ids)
        for layer in self.mtp:
            h = layer.forward_q(h, pos_t, input_ids, main_x, slot)
        return self.mtp[-1].forward_head(h, input_ids)

    @torch.inference_mode()
    def step_g(self, qin: torch.Tensor, pos_t: torch.Tensor, slot: int = 0, temp_t: torch.Tensor = None):
        """B1Q8 full speculative step, CUDA-graph-capturable, zero host work.
        qin [1, Q] int64: qin[0,0] = current token at pos_t, qin[0,1:] = draft tokens.
        temp_t: optional static float32 device [1] temperature; None/0 -> greedy argmax, >0 -> per-row
        Gumbel-max sample of the target (lossless: each accepted token is an exact target sample given
        its prefix). Sampled g is broadcast from rank 0 so all TP ranks accept identically.
        Verifies, accepts the longest draft prefix matching g (a in 0..Q-1), writes draft main_kv
        for all Q rows (rows past the accepted prefix are rewritten by the next step), drafts from the
        last accepted token, then updates qin / pos_t IN PLACE for the next replay.
        Returns (g [Q] int64 target token per row; g[:a+1] are the new tokens, n_new [1] = a+1, confidence)."""
        from ops.attn_decode_g import step_ctx_reset; step_ctx_reset()
        Q = qin.size(1)
        dev = qin.device
        logits, mh = self.forward_q_g(qin, pos_t, slot)
        lg = logits[0].to(torch.float32, copy=True)                        # [Q, V] (own buffer: masked in place)
        if temp_t is None:
            g = lg.argmax(-1)                                              # [Q]
        else:
            # argmax(lg + T * gumbel) == sample from softmax(lg / T); T == 0 degenerates to argmax.
            # nucleus_mask_ first zeroes (-1e30) everything outside top_p=TOP_P at temperature T.
            nucleus_mask_(lg, temp_t)
            u = torch.rand_like(lg).clamp_(1e-10, 1.0)
            g = (lg + temp_t * (-torch.log(-torch.log(u)))).argmax(-1)
            if dist.is_available() and dist.is_initialized() and dist.get_world_size() > 1:
                dist.broadcast(g, src=0)
        a = (qin[0, 1:] == g[:-1]).to(torch.int64).cumprod(0).sum().view(1)  # accepted drafts
        tok = g.index_select(0, a)                                         # [1] last accepted / next token
        main_pos = pos_t + torch.arange(Q, device=dev)
        h, main_x = self.mtp[0].forward_embed(mh, tok)                     # main_x [1, Q, .]
        qpos = pos_t + a
        for layer in self.mtp:
            h = layer.forward_q(h, qpos, tok, main_x, slot, main_pos)
        ids, _, conf = self.mtp[-1].forward_head(h, tok)                   # [1, block_size + 1], ids[0,0] == tok
        nb = ids.size(1)
        new_qin = torch.cat([ids[0], ids[0, -1:].expand(Q - nb)]) if Q > nb else ids[0, :Q]
        qin[0].copy_(new_qin)
        pos_t.add_(a + 1)
        return g, a + 1, conf


    def step_g_batch(self, qin: torch.Tensor, pos_t: torch.Tensor, slots, temp_t: torch.Tensor = None):
        """Batched (B rows x Q tokens) speculative step, CUDA-graph-capturable.

        qin [B, Q] int64: qin[b, 0] is row b's current token at pos_t[b], qin[b, 1:] its drafts.
        pos_t int64 device [B]; slots list[int]; temp_t optional float32 device [B] (per-row
        temperature, 0/None -> greedy).  Same contract as step_g, one row at a time:
        verify -> accept longest matching draft prefix -> MTP draft -> update qin/pos_t in place.
        The verify pass is shared across rows (one MoE weight read for all B*Q tokens); MTP layers
        stay per-row because their KV is slot-bound.  B == 1 mirrors step_g exactly.
        Returns (g [B, Q] target token per row, n_new [B] = accepted + 1, confidence).
        """
        from ops.attn_decode_g import step_ctx_reset; step_ctx_reset()
        B, Q = int(qin.size(0)), int(qin.size(1))
        dev = qin.device
        logits, mh = self.forward_q_g_batch(qin, pos_t, slots)
        lg = logits.to(torch.float32, copy=True)                             # [B, Q, V] (own buffer: masked in place)
        if temp_t is None:
            g = lg.argmax(-1)                                                # [B, Q]
        else:
            nucleus_mask_(lg, temp_t.view(B, 1, 1))                          # top_p=TOP_P per row
            u = torch.rand_like(lg).clamp_(1e-10, 1.0)
            g = (lg + temp_t.view(B, 1, 1) * (-torch.log(-torch.log(u)))).argmax(-1)
            if dist.is_available() and dist.is_initialized() and dist.get_world_size() > 1:
                dist.broadcast(g, src=0)
        a = (qin[:, 1:] == g[:, :-1]).to(torch.int64).cumprod(1).sum(1)      # [B] accepted drafts
        tok = g.gather(1, a.view(B, 1)).view(B)                              # [B] next token per row
        ar = torch.arange(Q, device=dev)
        h, main_x = self.mtp[0].forward_embed(mh, tok)                       # batched over rows
        qpos = pos_t + a                                                     # [B]
        # A4: all B rows through each MTP layer at once (projections / MoE / all_reduce shared);
        # only the slot-bound KV write + window attention is per row inside forward_qb.
        qpos_list = [qpos[b:b + 1] for b in range(B)]
        main_pos_list = [pos_t[b:b + 1] + ar for b in range(B)]
        for layer in self.mtp:
            h = layer.forward_qb(h, qpos_list, slots, tok, main_x, main_pos_list)
        ids, _, conf = self.mtp[-1].forward_head(h, tok)                     # [B, block_size + 1]
        nb = ids.size(1)
        new_qin = ids[:, :Q] if Q <= nb else torch.cat([ids, ids[:, -1:].expand(B, Q - nb)], dim=1)
        qin.copy_(new_qin)
        pos_t.add_(a + 1)
        return g, a + 1, conf


# Sampling policy is FIXED (no runtime knob, by design): temperature as requested (default 1.0),
# nucleus top_p = 0.95.  Basis: vLLM / SGLang SamplingParams default T=1.0,top_p=1.0; this model's
# generation_config.json T=1.0,top_p=1.0; DeepSeek-V4 README recommends T=1.0 + top_p=0.95 for
# agentic use (our main workload).  Greedy (T=0) is untouched: argmax, bit-identical to before.
TOP_P = 0.95
# FORK from the textbook full-vocab sort: nucleus is found inside the top-1024 window.  Measured on
# GPU7 (V=129280): full sort 1.4 ms (B1Q8) / 5.3 ms (B8Q8) vs a 29 ms decode step; topk-1024
# 0.33 / 1.0 ms.  Exact whenever the top-1024 tokens carry >= 95% mass (always true for peaked LM
# logits); on a pathologically flat distribution the cut is stricter, never looser.
TOP_P_WINDOW = 1024


def nucleus_mask_(lg: torch.Tensor, temp) -> torch.Tensor:
    """In place: set logits outside the top-p nucleus (evaluated at temperature `temp`) to -1e30.
    lg float [..., V]; temp float or tensor broadcastable to lg (per-row).  Top-1 is always kept, so
    temp -> 0 degenerates to the argmax token exactly."""
    t = torch.clamp(temp, min=1e-5) if torch.is_tensor(temp) else max(float(temp), 1e-5)
    p = torch.softmax(lg / t, dim=-1)
    tp, ti = p.topk(TOP_P_WINDOW, dim=-1)                                  # sorted desc
    keep_w = (tp.cumsum(dim=-1) - tp) < TOP_P                              # mass BEFORE token < p
    keep = torch.zeros_like(lg, dtype=torch.bool).scatter_(-1, ti, keep_w)
    return lg.masked_fill_(~keep, -1e30)


def sample(logits, temperature: float = 1.0):
    """Gumbel-max trick: equivalent to multinomial sampling but faster on GPU,
    since it avoids the GPU-to-CPU sync in torch.multinomial.  Nucleus top_p=TOP_P applied."""
    if temperature == 0:
        return logits.argmax(dim=-1)
    # copy=True: nucleus_mask_ is in place and must never touch the caller's logits
    lg = nucleus_mask_(logits.to(torch.float32, copy=True), temperature) / max(temperature, 1e-5)
    u = torch.rand_like(lg).clamp_(1e-10, 1.0)
    return (lg - torch.log(-torch.log(u))).argmax(dim=-1)


if __name__ == "__main__":
    torch.set_default_dtype(torch.bfloat16)
    torch.set_default_device("cuda")
    torch.manual_seed(0)
    args = ModelArgs(n_hash_layers=0, dspark_block_size=6, dspark_target_layer_ids=(5, 6))
    x = torch.randint(0, args.vocab_size, (2, 150))
    model = Transformer(args)

    output_ids, logits, main_hidden = model(x[:, :128])
    model.forward_spec(output_ids, main_hidden)
    for i in range(128, 150):
        output_ids, logits, main_hidden = model(x[:, i:i+1], i)
        output_ids, logits, confidence = model.forward_spec(output_ids, main_hidden, i)
